#+title: problem
#+author: Bartev
#+date: 2024-12-18
* Part 1

--- Day 18: RAM Run ---

You and The Historians look a lot more pixelated than you remember. You're inside a computer at the North Pole!

Just as you're about to check out your surroundings, a program runs up to you. "This region of memory isn't safe! The User misunderstood what a pushdown automaton is and their algorithm is pushing whole bytes down on top of us! Run!"

The algorithm is fast - it's going to cause a byte to fall into your memory space once every nanosecond! Fortunately, you're faster, and by quickly scanning the algorithm, you create a list of which bytes will fall (your puzzle input) in the order they'll land in your memory space.

Your memory space is a two-dimensional grid with coordinates that range from 0 to 70 both horizontally and vertically. However, for the sake of example, suppose you're on a smaller grid with coordinates that range from 0 to 6 and the following list of incoming byte positions:

#+begin_example
5,4
4,2
4,5
3,0
2,1
6,3
2,4
1,5
0,6
3,3
2,6
5,1
1,2
5,5
2,5
6,5
1,4
0,4
6,4
1,1
6,1
1,0
0,5
1,6
2,0
#+end_example
Each byte position is given as an X,Y coordinate, where X is the distance from the left edge of your memory space and Y is the distance from the top edge of your memory space.

You and The Historians are currently in the top left corner of the memory space (at 0,0) and need to reach the exit in the bottom right corner (at 70,70 in your memory space, but at 6,6 in this example). You'll need to simulate the falling bytes to plan out where it will be safe to run; for now, simulate just the first few bytes falling into your memory space.

As bytes fall into your memory space, they make that coordinate corrupted. Corrupted memory coordinates cannot be entered by you or The Historians, so you'll need to plan your route carefully. You also cannot leave the boundaries of the memory space; your only hope is to reach the exit.

In the above example, if you were to draw the memory space after the first 12 bytes have fallen (using . for safe and # for corrupted), it would look like this:

#+begin_example
...#...
..#..#.
....#..
...#..#
..#..#.
.#..#..
#.#....
#+end_example
You can take steps up, down, left, or right. After just 12 bytes have corrupted locations in your memory space, the shortest path from the top left corner to the exit would take 22 steps. Here (marked with O) is one such path:

#+begin_example
OO.#OOO
.O#OO#O
.OOO#OO
...#OO#
..#OO#.
.#.O#..
#.#OOOO
#+end_example
Simulate the first kilobyte (1024 bytes) falling onto your memory space. Afterward, what is the minimum number of steps needed to reach the exit?
** Clarification
I'm not sure if I'm supposed to move AFTER 1024 bytes have fallen, or while they're falling.
- yes, this is how it was
** Plan of attack
- Start with an empty grid, and add walls for every byte that falls
- Solve with BFS (dijkstra from puzzle 16)

** Answer

#+begin_example
────────────────────────────────────────── Part 1 ──────────────────────────────────────────
╭────────╮
│ Part 1 │
╰────────╯
part1 took 0.0001 seconds to run
test data: 22
part1 took 0.0052 seconds to run
Problem input: 416
example
* Part 2
--- Part Two ---

The Historians aren't as used to moving around in this pixelated universe as you are. You're afraid they're not going to be fast enough to make it to the exit before the path is completely blocked.

To determine how fast everyone needs to go, you need to determine the first byte that will cut off the path to the exit.

In the above example, after the byte at 1,1 falls, there is still a path to the exit:

#+begin_example
O..#OOO
O##OO#O
O#OO#OO
OOO#OO#
###OO##
.##O###
#.#OOOO
#+end_example
However, after adding the very next byte (at 6,1), there is no longer a path to the exit:

#+begin_example
...#...
.##..##
.#..#..
...#..#
###..##
.##.###
#.#....
#+end_example

So, in this example, the coordinates of the first byte that prevents the exit from being reachable are 6,1.

Simulate more of the bytes that are about to corrupt your memory space. What are the coordinates of the first byte that will prevent the exit from being reachable from your starting position? (Provide the answer as two integers separated by a comma with no other characters.)
** Plan of attack
- Modify the dijkstra algorith to return -1 if no solution is found
- create a dict {index: shortest path}
- keep track of the range of indices to check
  - starts at 0, len(moves)
- Do a binary search (runs in log time)
*** Algorithm
1. idx_start = 0
2. idx_end = len(moves)
3. add moves up to idx_end
4. if dijkestra finds a solution
   1. stop
   2. else
      1. There is a point between idx_start and idx_end that prevents solution
      2. idx_end = idx_start + (idx_end - idx_start) / 2
      3. Go to =3. add moves up to idx_end=



0-100
step 73 blocks

1. check 0 moves
2. passes.
3. check 100 moves
4. fails
5. Find 1/2 point between pass and fail (0-100 --> 50)
6. check if same as last end point (50 != 100, continue)
7. check 50 moves
8. passes
9. Find 1/2 point between pass and fail (50-100 --> 75)
10. check if same as last end point (75 != 100, continue)
12. fails
13. Find 1/2 point between pass and fail (50-75 --> 61)
14. passes
15. Find 1/2 point between pass and fail (61-75 --> 68)
16. passes
17. Find 1/2 point between pass and fail (68-75 --> 72)
18. passes
19. Find 1/2 point between pass and fail (72-75 --> 74)
20. fails
21. Find 1/2 point between pass and fail (72-74 --> 73)
22. fails
23. Find 1/2 point between pass and fail (72-73 --> 73)
24. check if same as last half-way point (same so stop)

how to find 1/2 way point?
round_up((start + end) / 2 )
** Answer

#+begin_example
────────────────────────────────────────── Part 1 ──────────────────────────────────────────
╭────────╮
│ Part 1 │
╰────────╯
part1 took 0.0001 seconds to run
test data: 22

part1 took 0.0053 seconds to run
Problem input: 416
────────────────────────────────────────── Part 2 ──────────────────────────────────────────
╭────────╮
│ Part 2 │
╰────────╯
binary search: (12, 25, 18)
binary search: (18, 25, 21)
binary search: (18, 21, 19)
binary search: (19, 21, 20)
part2 took 0.0002 seconds to run
test data: (6, 1)

binary search: (1725, 3450, 2587)
binary search: (2587, 3450, 3018)
binary search: (2587, 3018, 2802)
binary search: (2802, 3018, 2910)
binary search: (2802, 2910, 2856)
binary search: (2856, 2910, 2883)
binary search: (2856, 2883, 2869)
binary search: (2856, 2869, 2862)
binary search: (2862, 2869, 2865)
binary search: (2865, 2869, 2867)
binary search: (2867, 2869, 2868)
part2 took 0.0165 seconds to run
Problem input: (50, 23)
#+end_example
